// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { processLock } from '@supabase/auth-js';
import type { Database } from './types';
import { getSupabaseAuthStorageKey, getSupabaseBrowserUrl } from '@/lib/supabase-url';

const SUPABASE_URL = getSupabaseBrowserUrl();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const STORAGE_KEY = getSupabaseAuthStorageKey();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function clearInvalidStoredSession() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const parsed = JSON.parse(raw) as
      | { currentSession?: { refresh_token?: string | null } }
      | { refresh_token?: string | null }
      | null;
    // Supabase auth storage shape differs by sdk/version; only clear when we can
    // confidently determine a missing/invalid refresh token.
    const refreshToken =
      (parsed as { currentSession?: { refresh_token?: string | null } } | null)?.currentSession?.refresh_token ??
      (parsed as { refresh_token?: string | null } | null)?.refresh_token;
    if (typeof refreshToken === "string" && refreshToken.trim().length > 0) return;
    if (refreshToken === null || refreshToken === undefined) return;
    // Explicit empty token means stale/corrupt auth blob.
    if (typeof refreshToken === "string" && refreshToken.trim().length === 0) {
      localStorage.removeItem(STORAGE_KEY);
    }
  } catch {
    // Corrupted auth payload can also break refresh bootstrap.
    localStorage.removeItem(STORAGE_KEY);
  }
}

clearInvalidStoredSession();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    debug: false,
    // In-tab process lock avoids Navigator LockManager steal warnings from
    // concurrent getSession/refresh during React mount (see gotrue-js locks.ts).
    lock: processLock,
  },
  realtime: {
    // Avoid noisy reconnect loops when the tab is in the background.
    params: { eventsPerSecond: 2 },
  },
  global: {
    headers: {
      "X-Client-Info": "uddash-crm",
    },
  },
});

// Do not call refreshSession() at module load: it races with autoRefreshToken and other
// getSession/refresh callers, which triggers lock timeouts in @supabase/gotrue-js.
