// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const STORAGE_KEY = `sb-${new URL(SUPABASE_URL).hostname.split(".")[0]}-auth-token`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function clearInvalidStoredSession() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const parsed = JSON.parse(raw) as
      | { currentSession?: { refresh_token?: string | null } }
      | { refresh_token?: string | null }
      | null;
    // Supabase auth storage shape differs by sdk/version; only clear when we can
    // confidently determine a missing/invalid refresh token.
    const refreshToken =
      (parsed as { currentSession?: { refresh_token?: string | null } } | null)?.currentSession?.refresh_token ??
      (parsed as { refresh_token?: string | null } | null)?.refresh_token;
    if (typeof refreshToken === "string" && refreshToken.trim().length > 0) return;
    if (refreshToken === null || refreshToken === undefined) return;
    // Explicit empty token means stale/corrupt auth blob.
    if (typeof refreshToken === "string" && refreshToken.trim().length === 0) {
      localStorage.removeItem(STORAGE_KEY);
    }
  } catch {
    // Corrupted auth payload can also break refresh bootstrap.
    localStorage.removeItem(STORAGE_KEY);
  }
}

clearInvalidStoredSession();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
  }
});

void supabase.auth.getSession().then(async ({ data }) => {
  if (!data.session) return;
  const { error } = await supabase.auth.refreshSession();
  if (!error) return;
  if (/Invalid Refresh Token|Refresh Token Not Found/i.test(error.message || "")) {
    await supabase.auth.signOut({ scope: "local" });
  }
});
